[build]
  base = "apps/docs"
  command = "pnpm --dir ../.. --filter @drobinetm/countries-flags-core build && pnpm --dir ../.. --filter @drobinetm/react-countries-flags build && pnpm --dir ../.. --filter @drobinetm/vue-countries-flags build && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
